oro_entity_config:
    note:
        entity:
            items:
                enabled:
                    options:
                        enable_only:        true
                        schema_update:      true
                        priority:           250
                        default_value:      'No'
                        auditable:          false
                    form:
                        type:               choice
                        options:
                            block:          other
                            required:       true
                            label:          oro.note.entity_config.enabled.note_label
                            choices:        ['No', 'Yes']
                            empty_value:    false
                            empty_data:     'No'
