parameters:
    oro_note.form.extension.config_scope_type_extension.class:  Oro\Bundle\NoteBundle\Form\Extension\ConfigScopeTypeExtension

services:
    oro_note.form.extension.config_scope_type_extension:
        class: %oro_note.form.extension.config_scope_type_extension.class%
        arguments:
            - @oro_entity_config.provider.note
        tags:
            - { name: form.type_extension, alias: choice}
