parameters:
    oro_note.form.extension.note_extension.class:  Oro\Bundle\NoteBundle\Form\Extension\NoteExtension
    oro_note.form.type.note_choice.type.class:     Oro\Bundle\NoteBundle\Form\Type\NoteEnabledChoiceType

services:
    oro_note.form.type.note_choice.type:
        class: %oro_note.form.type.note_choice.type.class%
        tags:
            - { name: form.type, alias: note_choice }

    oro_note.form.extension.note_extension:
        class: %oro_note.form.extension.note_extension.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: form.type_extension, alias: note_choice}
