parameters:
    oro_note.form.extension.note_extension.class:  Oro\Bundle\NoteBundle\Form\Extension\NoteExtension
    oro_note.form.type.note_choice.type.class:     Oro\Bundle\NoteBundle\Form\Type\NoteEnabledChoiceType

    oro_note.form.type.note.class:                 Oro\Bundle\NoteBundle\Form\Type\NoteType
    oro_note.form.type.note_api.class:             Oro\Bundle\NoteBundle\Form\Type\NoteApiType
    oro_note.form.handler.note_api.class:          Oro\Bundle\NoteBundle\Form\Handler\NoteHandler

services:
    oro_note.form.type.note_choice.type:
        class: %oro_note.form.type.note_choice.type.class%
        tags:
            - { name: form.type, alias: note_choice }

    oro_note.form.extension.note_extension:
        class: %oro_note.form.extension.note_extension.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: form.type_extension, alias: note_choice}

    oro_note.form.type.note:
        class: %oro_note.form.type.note.class%
        tags:
            - { name: form.type, alias: oro_note }

    oro_note.form.type.note_api:
        class: %oro_note.form.type.note_api.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: form.type, alias: note }
