placeholders:
    view_navButtons_before:
        items:
            oro_add_note_button: ~

    view_content_data_additional_information:
        items:
            oro_notes:
                order: 255

items:
    oro_add_note_button:
        template: OroNoteBundle:Note:addButton.html.twig
        applicable: @oro_note.placeholder.filter->isNoteAssociationEnabled($entity$)

    oro_notes:
        template: OroNoteBundle:Note:notes.html.twig
        applicable: @oro_note.placeholder.filter->isNoteAssociationEnabled($entity$)
