parameters:
    oro_note.subscriber.note_lifecycle_subscriber.class: Oro\Bundle\NoteBundle\EventListener\NoteLifecycleSubscriber
    oro_note.entity_extend.generator_extension.class:    Oro\Bundle\NoteBundle\Tools\NoteExtendGenerator

services:
    oro_note.subscriber.note_lifecycle_subscriber:
        class: %oro_note.subscriber.note_lifecycle_subscriber.class%
        arguments:
            - @oro_security.security_facade.link
        tags:
            - { name: doctrine.event_subscriber }

    oro_note.entity_extend.generator_extension:
        class: %oro_note.entity_extend.generator_extension.class%
        tags:
            - { name: oro_entity_extend.generator_extension }
