parameters:
    oro_note.subscriber.note_lifecycle_subscriber.class: Oro\Bundle\NoteBundle\EventListener\NoteLifecycleSubscriber
    oro_note.entity_extend.generator_extension.class:    Oro\Bundle\NoteBundle\Tools\NoteExtendGenerator
    oro_note.placeholder.filter.class:                   Oro\Bundle\NoteBundle\Placeholder\Filter

services:
    oro_note.subscriber.note_lifecycle_subscriber:
        class: %oro_note.subscriber.note_lifecycle_subscriber.class%
        arguments:
            - @oro_security.security_facade.link
        tags:
            - { name: doctrine.event_subscriber }

    oro_note.entity_extend.generator_extension:
        class: %oro_note.entity_extend.generator_extension.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: oro_entity_extend.generator_extension, priority: 1 }

    oro_note.placeholder.filter:
        class: %oro_note.placeholder.filter.class%
        arguments:
            - @oro_entity_config.provider.note
            - @oro_entity.orm.entity_class_accessor
