parameters:
    oro_note.subscriber.note_lifecycle_subscriber.class: Oro\Bundle\NoteBundle\EventListener\NoteLifecycleSubscriber
    oro_note.entity_extend.generator_extension.class:    Oro\Bundle\NoteBundle\Tools\NoteExtendGenerator

    #entity
    oro_note.entity.class:      Oro\Bundle\NoteBundle\Entity\Note
    oro_note.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    #form
    oro_note.form.type.note.class:        Oro\Bundle\NoteBundle\Form\Type\NoteType
    oro_note.form.type.note_api.class:    Oro\Bundle\NoteBundle\Form\Type\NoteApiType
    oro_note.form.handler.note_api.class: Oro\Bundle\NoteBundle\Form\Handler\NoteHandler

services:
    oro_note.subscriber.note_lifecycle_subscriber:
        class: %oro_note.subscriber.note_lifecycle_subscriber.class%
        arguments:
            - @oro_security.security_facade.link
        tags:
            - { name: doctrine.event_subscriber }


    # !!!
    # FORMS  move to form.yml
    #
    oro_note.form.type.note:
        class: %oro_note.form.type.note.class%
        tags:
            - { name: form.type, alias: oro_note }

    oro_note.form.type.note_api:
        class: %oro_note.form.type.note_api.class%
        tags:
            - { name: form.type, alias: note }
    #
    # API
    #
    oro_note.manager.api:
        class: %oro_note.manager.api.class%
        arguments:
            - %oro_note.entity.class%
            - @doctrine.orm.entity_manager

    oro_note.form.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'note'
            - 'note'

    oro_note.form.handler.note_api:
        class: %oro_note.form.handler.note_api.class%
        scope: request
        arguments:
            - @oro_note.form.api
            - @request
            - @doctrine.orm.entity_manager


    oro_note.entity_extend.generator_extension:
        class: %oro_note.entity_extend.generator_extension.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: oro_entity_extend.generator_extension, priority: 1 }

