parameters:
    oro_note.entity.class:                              Oro\Bundle\NoteBundle\Entity\Note
    oro_note.note_lifecycle_listener.class:             Oro\Bundle\NoteBundle\EventListener\NoteLifecycleListener
    oro_note.placeholder.filter.class:                  Oro\Bundle\NoteBundle\Placeholder\Filter
    oro_note.migration.extension.note.class:            Oro\Bundle\NoteBundle\Migration\Extension\NoteExtension
    oro_note.entity_extend.dumper_extension.class:      Oro\Bundle\NoteBundle\Tools\NoteExtendConfigDumperExtension
    oro_note.entity_extend.generator_extension.class:   Oro\Bundle\NoteBundle\Tools\NoteExtendEntityGeneratorExtension
    oro_note.manager.class:                             Oro\Bundle\NoteBundle\Entity\Manager\EntityManager
    oro_note.manager.api.class:                         Oro\Bundle\NoteBundle\Entity\Manager\ApiEntityManager

services:
    oro_note.note_lifecycle_listener:
        class: %oro_note.note_lifecycle_listener.class%
        arguments:
            - @oro_security.security_facade.link
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    oro_note.manager:
        class: %oro_note.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.security_facade
            - @oro_security.acl_helper
            - @oro_locale.formatter.name
            - @oro_attachment.manager

    oro_note.manager.api:
        class: %oro_note.manager.api.class%
        arguments:
            - %oro_note.entity.class%
            - @doctrine.orm.entity_manager

    oro_note.placeholder.filter:
        class: %oro_note.placeholder.filter.class%
        arguments:
            - @oro_entity_config.provider.note
            - @oro_entity.orm.entity_class_accessor

    oro_note.entity_extend.dumper_extension:
        class: %oro_note.entity_extend.dumper_extension.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: oro_entity_extend.dumper_extension }

    oro_note.entity_extend.generator_extension:
        class: %oro_note.entity_extend.generator_extension.class%
        arguments:
        tags:
            - { name: oro_entity_extend.generator_extension }

    oro_note.migration.extension.note:
        class: %oro_note.migration.extension.note.class%
        tags:
            - { name: oro_migration.extension, extension_name: note }
