parameters:
    oro_note.entity.class:                              Oro\Bundle\NoteBundle\Entity\Note
    oro_note.note_lifecycle_listener.class:             Oro\Bundle\NoteBundle\EventListener\NoteLifecycleListener
    oro_note.placeholder.filter.class:                  Oro\Bundle\NoteBundle\Placeholder\PlaceholderFilter
    oro_note.migration.extension.note.class:            Oro\Bundle\NoteBundle\Migration\Extension\NoteExtension
    oro_note.entity_config_dumper.extension.class:      Oro\Bundle\NoteBundle\Tools\NoteEntityConfigDumperExtension
    oro_note.entity_generator.extension.class:          Oro\Bundle\NoteBundle\Tools\NoteEntityGeneratorExtension
    oro_note.manager.class:                             Oro\Bundle\NoteBundle\Entity\Manager\NoteManager
    oro_note.manager.api.class:                         Oro\Bundle\NoteBundle\Entity\Manager\ApiEntityManager

services:
    oro_note.note_lifecycle_listener:
        class: %oro_note.note_lifecycle_listener.class%
        arguments:
            - @oro_security.security_facade.link
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    oro_note.manager:
        class: %oro_note.manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.security_facade
            - @oro_security.acl_helper
            - @oro_locale.formatter.name
            - @oro_attachment.manager

    oro_note.manager.api:
        class: %oro_note.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %oro_note.entity.class%
            - @doctrine.orm.entity_manager

    oro_note.placeholder.filter:
        class: %oro_note.placeholder.filter.class%
        arguments:
            - @oro_entity_config.provider.note
            - @oro_entity_config.provider.entity

    oro_note.entity_config_dumper.extension:
        class: %oro_note.entity_config_dumper.extension.class%
        parent: oro_entity_extend.entity_config_dumper.extension.association
        tags:
            - { name: oro_entity_extend.entity_config_dumper_extension }

    oro_note.entity_generator.extension:
        class: %oro_note.entity_generator.extension.class%
        tags:
            - { name: oro_entity_extend.entity_generator_extension }

    oro_note.migration.extension.note:
        class: %oro_note.migration.extension.note.class%
        tags:
            - { name: oro_migration.extension, extension_name: note }
