parameters:
    oro_note.subscriber.note_lifecycle_subscriber.class: Oro\Bundle\NoteBundle\EventListener\NoteLifecycleSubscriber

services:
    oro_note.subscriber.note_lifecycle_subscriber:
        class: %oro_note.subscriber.note_lifecycle_subscriber.class%
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_subscriber }
