api:
    entities:
        Oro\Bundle\NoteBundle\Entity\Note:
            fields:
                target:
                    description: A record to which the Note record belongs to
                    data_type: association:manyToOne
            subresources:
                target:
                    actions:
                        get_subresource:
                            documentation: Get full information about a record to which the note belongs to
                        get_relationship:
                            documentation: Get a record to which the note belongs to
                        update_relationship:
                            documentation: Update a record to which the note belongs to
